Albania is awesome
=============
```{r load, echo=FALSE, results='hide', warning = FALSE, message=FALSE}
library(ggplot2)
library(dplyr)
setwd("..")
sets <- c("school", "student")

# function to build the file names
fn_build <- function(file_name) {
    template <- c("2012.rda", "2012dict.rda")
    file_name %>% vapply(paste0, template, template) %>% file.path(".", "data", 
        .)
}

# load the data
sets %>% fn_build %>% lapply(load, .GlobalEnv)

# function to convert to data-frames
fn_make_df <- function(named_vector) {
    data.frame(variable = attr(named_vector, "names"), description = named_vector, 
        row.names = NULL)
}

dict_school2012 <- fn_make_df(school2012dict)
dict_student2012 <- fn_make_df(student2012dict)
rm(fn_make_df, fn_build, sets, school2012dict, student2012dict)

student2012$math = as.numeric(student2012[, "PV1MATH"])
student2012$read = as.numeric(student2012[, "PV1READ"])
student2012$sci = as.numeric(student2012[, "PV1SCIE"])

#separate albania
student2012$OECD = as.character(student2012$OECD)
student2012[student2012$CNT == "Albania", ]$OECD = "Albania"
```

```{r vars, echo=FALSE}
student2012.sub = student2012 %>% select(CNT, SCHOOLID, math, read, sci, OUTHOURS, STIDSTD, ST04Q01, ST11Q01, ST11Q02, ST15Q01, ST19Q01, ST26Q01, ST26Q02, ST26Q03, ST26Q04, ST26Q05, ST26Q06, ST26Q07, ST26Q08, ST26Q09, ST26Q10, ST26Q11, ST26Q12, ST26Q13, ST26Q14, ST27Q01, ST27Q02, ST27Q03, ST27Q04, ST27Q05, ST28Q01, OECD)

for (i in 13:26) {
    student2012.sub[, i] <- as.character(student2012.sub[, i])
    student2012.sub[is.na(student2012.sub[, i]), i] <- ""
    student2012.sub[student2012.sub[, i] == "Yes", i] <- "1"
    student2012.sub[student2012.sub[, i] == "No", i] <- "0"
    student2012.sub[, i] <- as.numeric(student2012.sub[, i])
}
for (i in 27:31) {
    student2012.sub[, i] <- as.character(student2012.sub[, i])
    student2012.sub[is.na(student2012.sub[, i]), i] <- ""
    student2012.sub[student2012.sub[, i] == "None", i] <- "0"
    student2012.sub[student2012.sub[, i] == "One", i] <- "1"
    student2012.sub[student2012.sub[, i] == "Two", i] <- "2"
    student2012.sub[student2012.sub[, i] == "Three or more", i] <- "3"
    student2012.sub[, i] <- as.numeric(student2012.sub[, i])
}
student2012.sub[, 32] <- as.character(student2012.sub[, 32])
student2012.sub[is.na(student2012.sub[,32]), 32] <- ""
student2012.sub[student2012.sub[, 32] == "0-10 books ", 32] <- "0"
student2012.sub[student2012.sub[, 32] == "11-25 books ", 32] <- "1"
student2012.sub[student2012.sub[, 32] == "26-100 books ", 32] <- "2"
student2012.sub[student2012.sub[, 32] == "101-200 books ", 32] <- "3"
student2012.sub[student2012.sub[, 32] == "201-500 books ", 32] <- "4"
student2012.sub[student2012.sub[, 32] == "More than 500 books", 32] <- "5"
student2012.sub[, 32] <- as.numeric(student2012.sub[, 32])

#aggregate possessions
student2012.sub$numposs <- apply(student2012.sub[, 13:26], 1, sum, na.rm = T)
student2012.sub$numedposs <- apply(student2012.sub[, 27:31], 1, sum, na.rm = T)
```

```{r possessions, echo=FALSE, fig.width=15, warning=FALSE, message=FALSE}
library(reshape2)

df = melt(student2012.sub %>% group_by(CNT, numposs, OECD) %>% summarise(mmath = mean(math), msci = mean(sci), mread = mean(read)), id=c("CNT", "numposs", "OECD"))

df$group = paste0(df$CNT, df$variable)
qplot(x = numposs, y = value, data = df, facets = ~OECD, geom = "line", color = variable, group = group) + ylab("test scores") + xlab("number of possessions") + scale_colour_discrete(name = "Subject", labels=c("Math", "Science", "Reading"))

qplot(x = numposs, y = mmath, data = student2012.sub %>% group_by(CNT, numposs, OECD) %>% summarise(mmath = mean(math), msci = mean(sci), mread = mean(read)), facets =~OECD, geom = "line", group = CNT) + ylab("math Scores")
```


```{r OUTHOURS, echo=FALSE, fig.width=15, warning=FALSE, message=FALSE}
ggplot(subset(student2012.sub, !is.na(OUTHOURS)), aes(x = OUTHOURS, fill = CNT)) + geom_density(alpha = I(0.4)) + facet_wrap(~OECD) + theme(legend.position = "none") + scale_x_continuous("out of school study time (hours)", limits = c(0, 65))

qplot(x = OUTHOURS, data = student2012.sub, geom = "density", facets = ~CNT, fill = I("grey")) 
qplot(x = OUTHOURS, data = student2012.sub %>% filter(CNT == "Albania"), geom="density", fill = I("grey"))
qplot(x = OUTHOURS, data = student2012.sub %>% filter(CNT == "Albania"))
```

```{r parentjobs, echo=FALSE, fig.width=15}
father.df = melt(student2012 %>% select(CNT, ST15Q01, ST19Q01, math, sci, read, OECD) %>% group_by(ST15Q01, CNT, OECD) %>% summarise(math = mean(math), sci = mean(sci), read = mean(read)), id = c("CNT", "OECD", "ST15Q01"))
father.df$group = paste0(father.df$CNT, father.df$variable)
levels(father.df$ST15Q01) = c("full time", "part time", "unemployed", "retired")

qplot(x = ST15Q01, y = value, color = variable, facets = ~OECD, data = father.df, group = group, geom = "line") + xlab("father's employment status") + ylab("test scores") + scale_colour_discrete(name = "Subject", labels=c("Math", "Science", "Reading"))
```


```{r truancyschool, echo=FALSE, fig.width=15}
school2012.sub = school2012 %>% select(CNT, SCHOOLID, SC22Q01)
student2012.sub = student2012 %>% select(CNT, SCHOOLID, math, read, sci, OECD)
truancy.df = melt( student2012.sub %>% 
  group_by(CNT, SCHOOLID) %>% 
  left_join(school2012.sub, by = c("CNT", "SCHOOLID")) %>% 
  group_by(CNT, SC22Q01, OECD) %>% summarise(math = mean(math), read = mean(read), sci = mean(sci)), 
  id = c("CNT", "SC22Q01", "OECD")) %>% filter(!is.na(SC22Q01))
truancy.df$group = paste0(truancy.df$CNT, truancy.df$variable)

qplot(x = SC22Q01, y = value, color = variable, facets = ~OECD, data = truancy.df, group = group, geom = "line") + xlab("reported truancy") + ylab("test scores") + scale_colour_discrete(name = "Subject", labels=c("Math", "Science", "Reading"))
```


```{r gendergap, echo=FALSE, warning = FALSE, fig.height = 10}
scores = student2012 %>%
  select(CNT, math, read, ST04Q01, OECD) %>% 
  group_by(OECD, CNT, ST04Q01) %>%
  summarise(math = mean(math), read = mean(read))
male = scores %>% filter(ST04Q01 == "Male")
female = scores %>% filter(ST04Q01 == "Female")
scores.df = data.frame(OECD = male$OECD, CNT = male$CNT, math_difference = male$math - female$math, read_difference = male$read - female$read)


scores.df$CNT = factor(scores.df$CNT, levels = scores.df$CNT[order(scores.df$math_difference)])
qplot(CNT, math_difference, data = scores.df, color = OECD, size = OECD) + coord_flip() +
  scale_y_continuous("math score gap: male - female scores", breaks=seq(-30, 30, 5)) +
  geom_hline(yintercept=0, colour="grey80") + scale_size_manual(values = c(4, 2.5, 2.5)) + xlab("")



scores.df$CNT = factor(scores.df$CNT, levels = scores.df$CNT[order(scores.df$read_difference)])
qplot(CNT, read_difference, data = scores.df, color = OECD, size = OECD) + coord_flip() +
  scale_y_continuous("read score gap: male - female scores") +
  geom_hline(yintercept=0, colour="grey80") + scale_size_manual(values = c(4, 2.5, 2.5)) + xlab("")

#qplot(CNT, value, data = melt(scores.df, id = c("OECD", "CNT")), color = OECD, size = OECD, facets = ~variable) + 
#  coord_flip() + xlab("") + ylab("Score difference: male - female") + scale_size_manual(values = c(4, 2.5, 2.5))
```

```{r another idea}
.width = 1

data_small <- 
  student2012 %>%
  select(OECD, CNT, OUTHOURS) %>%
  filter(!is.na(OUTHOURS))

ggplot(mapping = aes(x = OUTHOURS)) + 
  geom_histogram(
    mapping = aes(y = ..density.., fill = OECD), 
    binwidth = .width,
    data = data_small %>% filter(OECD == "Albania")
  ) + 
  geom_line(
    mapping = aes(group = CNT, color = OECD), 
    stat = "density", 
    alpha = 0.3,
    data = data_small %>% filter(OECD != "Albania")
  ) 
```
