Schools
========================================================
```{r load, cache=TRUE, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
library(ggplot2)
library(dplyr)
setwd("..")
sets <- c("item", "parent", "school", "scoredItem", "student")

# function to build the file names
fn_build <- function(file_name) {

    template <- c("2012.rda", "2012dict.rda")

    file_name %>% vapply(paste0, template, template) %>% file.path(".", "data", 
        .)
}

# load the data
sets %>% fn_build %>% lapply(load, .GlobalEnv)


# function to convert to data-frames
fn_make_df <- function(named_vector) {
    data.frame(variable = attr(named_vector, "names"), description = named_vector, 
        row.names = NULL)
}

# there's a clever way to do this, but beyond me for naw
dict_item2012 <- fn_make_df(item2012dict)
dict_parent2012 <- fn_make_df(parent2012dict)
dict_school2012 <- fn_make_df(school2012dict)
dict_scoredItem2012 <- fn_make_df(scoredItem2012dict)
dict_student2012 <- fn_make_df(student2012dict)

rm(fn_make_df, fn_build, sets, item2012dict, parent2012dict, school2012dict, scoredItem2012dict, student2012dict)

student2012$math = as.numeric(student2012[, "PV1MATH"])
student2012$read = as.numeric(student2012[, "PV1READ"])
student2012$sci = as.numeric(student2012[, "PV1SCIE"])
```


mean number of possessions grouped by CNT and SCHOOLID
```{r countpossessions, warning=FALSE, message=FALSE}
student2012.sub <- student2012[, c(1:7, 44:57, 61:66, seq(501, 550, 5))]
colnames(student2012.sub)[1] <- "name"
for (i in 8:21) {
  student2012.sub[,i] <- as.character(student2012.sub[,i])
  student2012.sub[is.na(student2012.sub[,i]), i] <- ""
  student2012.sub[student2012.sub[,i]=="Yes",i] <- "1"
  student2012.sub[student2012.sub[,i]=="No",i] <- "0"
  student2012.sub[,i] <- as.numeric(student2012.sub[,i])
}
for (i in 22:26) {
  student2012.sub[,i] <- as.character(student2012.sub[,i])
  student2012.sub[is.na(student2012.sub[,i]), i] <- ""
  student2012.sub[student2012.sub[,i]=="None",i] <- "0"
  student2012.sub[student2012.sub[,i]=="One",i] <- "1"
  student2012.sub[student2012.sub[,i]=="Two",i] <- "2"
  student2012.sub[student2012.sub[,i]=="Three or more",i] <- "3"
  student2012.sub[,i] <- as.numeric(student2012.sub[,i])
}
student2012.sub[,27] <- as.character(student2012.sub[,27])
student2012.sub[is.na(student2012.sub[,27]), 27] <- ""
student2012.sub[student2012.sub[,27]=="0-10 books ",27] <- "0"
student2012.sub[student2012.sub[,27]=="11-25 books ",27] <- "1"
student2012.sub[student2012.sub[,27]=="26-100 books ",27] <- "2"
student2012.sub[student2012.sub[,27]=="101-200 books ",27] <- "3"
student2012.sub[student2012.sub[,27]=="201-500 books ",27] <- "4"
student2012.sub[student2012.sub[,27]=="More than 500 books",27] <- "5"
student2012.sub[,27] <- as.numeric(student2012.sub[,27])
student2012.sub$numposs <- apply(student2012.sub[,8:21], 1, sum, na.rm=T)
student2012.sub$numedposs <- apply(student2012.sub[,22:27], 1, sum, na.rm=T)

library(ggplot2)
library(dplyr)
student2012.sub$PV1MATH = as.numeric(student2012.sub$PV1MATH)
qplot(mnumposs, mmath, data = student2012.sub %>% select(name, SCHOOLID, numposs, PV1MATH) %>% group_by(name, SCHOOLID) %>% summarise(mmath = mean(PV1MATH), mnumposs = mean(numposs)), facets = ~name)

```

Hard to see in this document but if you zoom in there's a pretty clear positive correlation.