Exploring maps
========================================================


```{r load_libraries, message=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
library(ggplot2)
library(dplyr)
library(lubridate)
library(ggvis)
library(maps)
library(ggmap)
library(rworldmap)
library (grid)  	
library (scales)	
```

```{r load_data, echo=FALSE, warning=FALSE, message=FALSE}
setwd("..")
sets <- c("item", "parent", "school", "scoredItem", "student")

# function to build the file names
fn_build <- function(file_name){
 
  template <- c("2012.rda", "2012dict.rda")
 
  file_name %>% 
    vapply(str_join, template, template) %>% 
    file.path(".", "data", .)
}

# load the data
sets %>% fn_build %>% lapply(load, .GlobalEnv)

# clean
#rm(fn_build, sets)
```

```{r modify_dictionaries, echo=FALSE, warning=FALSE, message=FALSE}
# function to convert to data-frames
fn_make_df <- function(named_vector){
  data.frame(
    variable = attr(named_vector, "names"),
    description = named_vector,
    row.names = NULL
  )
}

# there's a clever way to do this, but beyond me for naw
dict_item2012 <- fn_make_df(item2012dict) 
dict_parent2012 <- fn_make_df(parent2012dict) 
dict_school2012 <- fn_make_df(school2012dict) 
dict_scoredItem2012 <- fn_make_df(scoredItem2012dict) 
dict_student2012 <- fn_make_df(student2012dict) 

# clean
#rm(fn_make_df)
#rm(item2012dict, parent2012dict, school2012dict, scoredItem2012dict, student2012dict)
```

```{r usefulfn, echo=FALSE, warning=FALSE, message=FALSE}
extractPolygons <- function(shapes) {

  dframe <- ldply(1:length(shapes@polygons), function(i) {
    ob <- shapes@polygons[[i]]@Polygons
    dframe <- ldply(1:length(ob), function(j) {
      x <- ob[[j]]
      co <- x@coords
      data.frame(co, order=1:nrow(co), group=j)
    })
    dframe$region <- i
    dframe$name <- shapes@polygons[[i]]@ID
    dframe$area <- shapes@polygons[[i]]@area
    dframe
  })
  # construct a group variable from both group and polygon:
  dframe$group <- interaction(dframe$region, dframe$group)
  
  dframe
}

# To get a blank background on map
new_theme_empty <- theme_bw()
new_theme_empty$line <- element_blank()
new_theme_empty$rect <- element_blank()
new_theme_empty$strip.text <- element_blank()
new_theme_empty$axis.text <- element_blank()
new_theme_empty$plot.title <- element_blank()
new_theme_empty$axis.title <- element_blank()
new_theme_empty$plot.margin <- structure(c(0, 0, -1, -1), unit = "lines", valid.unit = 3L, class = "unit")
```

```{r summarize, warning=FALSE, message=FALSE}
sort(table(student2012$CNT))
schools.sampled <- summarise(group_by(student2012[,c(1,6)], CNT), numschools=length(unique(SCHOOLID)))
schools.sampled[order(schools.sampled$numschools, decreasing=T),]
```

```{r maps, fig.width=12, fig.height=7, warning=FALSE, message=FALSE}
# Extract map polygons for modern world
world <- getMap(resolution = "low")
library(plyr)
world.polys <- extractPolygons(world)
detach("package:plyr")
# Subset data
student2012.sub <- student2012[, c(1:7, seq(501, 550, 5))]
colnames(student2012.sub)[1] <- "name"
student2012.sub$name <- as.character(student2012.sub$name)
# Check mismatches of names
# unique(anti_join(student2012.sub, world.polys)[1])
student2012.sub$name[student2012.sub$name=="Serbia"] <- "Republic of Serbia"
student2012.sub$name[student2012.sub$name=="Korea"] <- "South Korea"
student2012.sub$name[student2012.sub$name=="Chinese Taipei"] <- "Taiwan"
student2012.sub$name[student2012.sub$name=="Slovak Republic"] <- "Slovakia"
student2012.sub$name[student2012.sub$name=="Russian Federation"] <- "Russia"
student2012.sub$name[student2012.sub$name=="Perm(Russian Federation)"] <- "Russia"
student2012.sub$name[student2012.sub$name=="Hong Kong-China"] <- "Hong Kong S.A.R."
student2012.sub$name[student2012.sub$name=="China-Shanghai"] <- "China"
student2012.sub$name[student2012.sub$name=="China-Macau"] <- "China"
student2012.sub$name[student2012.sub$name=="Connecticut (USA)"] <- "United States of America"
student2012.sub$name[student2012.sub$name=="Florida (USA)"] <- "United States of America"
student2012.sub$name[student2012.sub$name=="Massachusetts (USA)"] <- "United States of America"

# Only need one of the plausible values, checked they are effectively identical
student2012.sub$PV1MATH <- as.numeric(student2012.sub$PV1MATH)
student2012.sub$PV1MACC <- as.numeric(student2012.sub$PV1MACC)
student2012.sub$PV1MACQ <- as.numeric(student2012.sub$PV1MACQ)
student2012.sub$PV1MACS <- as.numeric(student2012.sub$PV1MACS)
student2012.sub$PV1MACU <- as.numeric(student2012.sub$PV1MACU)
student2012.sub$PV1MAPE <- as.numeric(student2012.sub$PV1MAPE)
student2012.sub$PV1MAPF <- as.numeric(student2012.sub$PV1MAPF)
student2012.sub$PV1MAPI <- as.numeric(student2012.sub$PV1MAPI)
student2012.sub$PV1READ <- as.numeric(student2012.sub$PV1READ)
student2012.sub$PV1SCIE <- as.numeric(student2012.sub$PV1SCIE)
student2012.sub.summary <- summarise(group_by(student2012.sub[,c(1,8:17)], name), math=mean(PV1MATH, na.rm=T), 
                                  mCC=mean(PV1MACC, na.rm=T), mCQ=mean(PV1MACQ, na.rm=T), 
                                  mCS=mean(PV1MACS, na.rm=T), mCU=mean(PV1MACU, na.rm=T), 
                                  mPE=mean(PV1MAPE, na.rm=T), mPF=mean(PV1MAPF, na.rm=T), 
                                  mPI=mean(PV1MAPI, na.rm=T), read=mean(PV1READ, na.rm=T), 
                                  science=mean(PV1SCIE, na.rm=T), 
                                     mathr=diff(range(PV1MATH, na.rm=T)), 
                                  mCCr=diff(range(PV1MACC, na.rm=T)), mCQr=diff(range(PV1MACQ, na.rm=T)), 
                                  mCSr=diff(range(PV1MACS, na.rm=T)), mCUr=diff(range(PV1MACU, na.rm=T)), 
                                  mPEr=diff(range(PV1MAPE, na.rm=T)), mPFr=diff(range(PV1MAPF, na.rm=T)), 
                                  mPIr=diff(range(PV1MAPI, na.rm=T)), readr=diff(range(PV1READ, na.rm=T)), 
                                  sciencer=diff(range(PV1SCIE, na.rm=T)))
colnames(student2012.sub.summary)[3:9] <- c("Change", "Quantity", "Spatial", "Data", "Employ", "Formulate", "Interpret")

# Left join to only get countries that are measured
student2012.sub.map <- left_join(student2012.sub.summary, world.polys)
#qplot(X1, X2, order=order, group=group, data=student2012.sub.map, geom="polygon", fill=math) + coord_map() + new_theme_empty

# Really need all boundaries, doesn't quite work to have boundaries with one data: coord_map is the problem
ggplot(data=world.polys) + geom_path(aes(x=X1, y=X2, order=order, group=group), colour=I("grey70")) + 
  geom_polygon(data=student2012.sub.map, aes(x=X1, y=X2, order=order, group=group, fill=math)) +
  new_theme_empty + theme(legend.position="none")

# Now try to do an insert
# Note China is represented just Shanghai and Macau
# Individual states in the USA, Florida, Mass, Conn are included as US
# Russian Federation has two groups intributinf
student2012.sub.summary$name <- factor(student2012.sub.summary$name, 
      levels=student2012.sub.summary$name[order(student2012.sub.summary$math)])
p1 <- ggplot(data=world.polys) + geom_path(aes(x=X1, y=X2, order=order, group=group), colour=I("grey70")) + 
  geom_polygon(data=student2012.sub.map, aes(x=X1, y=X2, order=order, group=group, fill=math)) +
  new_theme_empty + theme(legend.position="none")
p2 <- qplot(name, math, data=student2012.sub.summary, colour=math, ylab="Math Score", xlab="") + coord_flip() + 
  theme(legend.position="none")
p2 = ggplotGrob(p2)  			
p1 + annotation_custom(grob = p2, xmin = -40, xmax = 80, ymin = -110, ymax = 10)

student2012.sub.summary$name <- factor(student2012.sub.summary$name, 
      levels=student2012.sub.summary$name[order(student2012.sub.summary$mathr)])
p1 <- ggplot(data=world.polys) + geom_path(aes(x=X1, y=X2, order=order, group=group), colour=I("grey70")) + 
  geom_polygon(data=student2012.sub.map, aes(x=X1, y=X2, order=order, group=group, fill=mathr)) +
  new_theme_empty + theme(legend.position="none")
p2 <- qplot(name, mathr, data=student2012.sub.summary, colour=mathr, ylab="Range Math", xlab="") + coord_flip() + 
  theme(legend.position="none")
p2 = ggplotGrob(p2)    		
p1 + annotation_custom(grob = p2, xmin = -40, xmax = 80, ymin = -110, ymax = 10)

# Reading
student2012.sub.summary$name <- factor(student2012.sub.summary$name, 
      levels=student2012.sub.summary$name[order(student2012.sub.summary$read)])
p1 <- ggplot(data=world.polys) + geom_path(aes(x=X1, y=X2, order=order, group=group), colour=I("grey70")) + 
  geom_polygon(data=student2012.sub.map, aes(x=X1, y=X2, order=order, group=group, fill=read)) +
  new_theme_empty + theme(legend.position="none")
p2 <- qplot(name, read, data=student2012.sub.summary, colour=read, ylab="Reading Score", xlab="") + coord_flip() + 
  theme(legend.position="none")
p2 = ggplotGrob(p2)    		
p1 + annotation_custom(grob = p2, xmin = -40, xmax = 80, ymin = -110, ymax = 10)

student2012.sub.summary$name <- factor(student2012.sub.summary$name, 
      levels=student2012.sub.summary$name[order(student2012.sub.summary$readr)])
p1 <- ggplot(data=world.polys) + geom_path(aes(x=X1, y=X2, order=order, group=group), colour=I("grey70")) + 
  geom_polygon(data=student2012.sub.map, aes(x=X1, y=X2, order=order, group=group, fill=readr)) +
  new_theme_empty + theme(legend.position="none")
p2 <- qplot(name, readr, data=student2012.sub.summary, colour=readr, ylab="Range Reading", xlab="") + coord_flip() + 
  theme(legend.position="none")
p2 = ggplotGrob(p2)    		
p1 + annotation_custom(grob = p2, xmin = -40, xmax = 80, ymin = -110, ymax = 10)

# Science
student2012.sub.summary$name <- factor(student2012.sub.summary$name, 
      levels=student2012.sub.summary$name[order(student2012.sub.summary$science)])
p1 <- ggplot(data=world.polys) + geom_path(aes(x=X1, y=X2, order=order, group=group), colour=I("grey70")) + 
  geom_polygon(data=student2012.sub.map, aes(x=X1, y=X2, order=order, group=group, fill=science)) +
  new_theme_empty + theme(legend.position="none")
p2 <- qplot(name, science, data=student2012.sub.summary, colour=science, ylab="Science Score", xlab="") + coord_flip() + 
  theme(legend.position="none")
p2 = ggplotGrob(p2)      	
p1 + annotation_custom(grob = p2, xmin = -40, xmax = 80, ymin = -110, ymax = 10)

student2012.sub.summary$name <- factor(student2012.sub.summary$name, 
      levels=student2012.sub.summary$name[order(student2012.sub.summary$sciencer)])
p1 <- ggplot(data=world.polys) + geom_path(aes(x=X1, y=X2, order=order, group=group), colour=I("grey70")) + 
  geom_polygon(data=student2012.sub.map, aes(x=X1, y=X2, order=order, group=group, fill=sciencer)) +
  new_theme_empty + theme(legend.position="none")
p2 <- qplot(name, sciencer, data=student2012.sub.summary, colour=sciencer, ylab="Range Science", xlab="") + coord_flip() + 
  theme(legend.position="none")
p2 = ggplotGrob(p2)    		
p1 + annotation_custom(grob = p2, xmin = -40, xmax = 80, ymin = -110, ymax = 10)
```

```{r all, fig.width=8, fig.height=12, warning=FALSE, message=FALSE}
student2012.sub.iqr <- summarise(group_by(student2012.sub[,c(1,8:17)], name), q0=min(PV1MATH, na.rm=T),
                                 q25=quantile(PV1MATH, 0.25, na.rm=T), q50=median(PV1MATH, na.rm=T), 
                                 q75=quantile(PV1MATH, 0.75, na.rm=T), q100=max(PV1MATH, na.rm=T), 
                                 count=length(PV1MATH))
student2012.sub.iqr$name <- factor(student2012.sub.iqr$name, 
      levels=student2012.sub.summary$name[order(student2012.sub.summary$math)])
ggplot(data=student2012.sub.iqr) + ylab("Math Score") + xlab("") + ylim(c(0,1000)) + 
  geom_point(aes(x=name, y=q50, size=count)) + geom_segment(aes(x=name, xend=name, y=q0, yend=q25)) +
  geom_segment(aes(x=name, xend=name, y=q75, yend=q100)) +
  coord_flip() + theme(legend.position="none")
student2012.sub.iqr <- summarise(group_by(student2012.sub[,c(1,8:17)], name), q0=min(PV1READ, na.rm=T),
                                 q25=quantile(PV1READ, 0.25, na.rm=T), q50=median(PV1READ, na.rm=T), 
                                 q75=quantile(PV1READ, 0.75, na.rm=T), q100=max(PV1READ, na.rm=T), 
                                 count=length(PV1READ))
student2012.sub.iqr$name <- factor(student2012.sub.iqr$name, 
      levels=student2012.sub.summary$name[order(student2012.sub.summary$read)])
ggplot(data=student2012.sub.iqr) + ylab("Reading Score") + xlab("") + ylim(c(0,1000)) + 
  geom_point(aes(x=name, y=q50, size=count)) + geom_segment(aes(x=name, xend=name, y=q0, yend=q25)) +
  geom_segment(aes(x=name, xend=name, y=q75, yend=q100)) +
  coord_flip() + theme(legend.position="none")
student2012.sub.iqr <- summarise(group_by(student2012.sub[,c(1,8:17)], name), q0=min(PV1SCIE, na.rm=T),
                                 q25=quantile(PV1SCIE, 0.25, na.rm=T), q50=median(PV1SCIE, na.rm=T), 
                                 q75=quantile(PV1SCIE, 0.75, na.rm=T), q100=max(PV1SCIE, na.rm=T), 
                                 count=length(PV1SCIE))
student2012.sub.iqr$name <- factor(student2012.sub.iqr$name, 
      levels=student2012.sub.summary$name[order(student2012.sub.summary$science)])
ggplot(data=student2012.sub.iqr) + ylab("Science Score") + xlab("") + ylim(c(0,1000)) + 
  geom_point(aes(x=name, y=q50, size=count)) + geom_segment(aes(x=name, xend=name, y=q0, yend=q25)) +
  geom_segment(aes(x=name, xend=name, y=q75, yend=q100)) +
  coord_flip() + theme(legend.position="none")
```

```{r oz, fig.width=8, fig.height=12, warning=FALSE, message=FALSE}
# Why is australia so varied?
student2012.sub.oz <- student2012.sub[student2012.sub$name=="Australia",]
student2012.sub.oz$SCHOOLID <- as.character(student2012.sub.oz$SCHOOLID)
#table(student2012.sub.oz$SCHOOLID)
#length(unique(student2012.sub.oz$SCHOOLID))
student2012.sub.oz.mean <- summarise(group_by(student2012.sub[,c(1,6, 8)], SCHOOLID), math=mean(PV1MATH, na.rm=T), 
                                     q0=min(PV1MATH, na.rm=T), q25=quantile(PV1MATH, p=0.25, na.rm=T), 
                                     q50=median(PV1MATH, na.rm=T),
                                     q75=quantile(PV1MATH, p=0.75, na.rm=T), q100=max(PV1MATH, na.rm=T))
student2012.sub.oz.mean$SCHOOLID <- factor(student2012.sub.oz.mean$SCHOOLID, levels=student2012.sub.oz.mean$SCHOOLID[order(student2012.sub.oz.mean$q50)])
ggplot(data=student2012.sub.oz.mean) + ylab("Math Score") + xlab("") + 
  geom_point(aes(x=SCHOOLID, y=q50)) + geom_segment(aes(x=SCHOOLID, xend=SCHOOLID, y=q0, yend=q25), alpha=0.1) +
  geom_segment(aes(x=SCHOOLID, xend=SCHOOLID, y=q75, yend=q100), alpha=0.1) +
  coord_flip() + theme(legend.position="none")
# So mostly the variation is student to student, not school to school like a friend suggested
# Not the best way to display this, I think
# Really want to be able to show that the best student at a low scoring school does better 
# than the worst student at a high-scoring school
```

```{r schoolmath, fig.width=12, fig.height=12, warning=FALSE, message=FALSE}
# Wonder how other countries compare
student2012.sub <- student2012[, c(1, 6, 501)]
colnames(student2012.sub)[1] <- "name"
student2012.sub$PV1MATH <- as.numeric(student2012.sub$PV1MATH)
student2012.sub.summary <- summarise(group_by(student2012.sub, name, SCHOOLID), math=median(PV1MATH, na.rm=T))
student2012.sub.summary$SCHOOLID <- as.numeric(as.character(student2012.sub.summary$SCHOOLID))
order <- summarise(group_by(student2012.sub, name, SCHOOLID), math=median(PV1MATH, na.rm=T))
bymedian <- with(student2012.sub.summary, reorder(name, math, median))
qplot(bymedian, math, data=student2012.sub.summary, ylim=c(0,1000), xlab="Math", ylab="") + coord_flip()
# Pretty similar overall, Australia still comes up as having a big variance, a few low-scoring schools 
# and a few high-scoring schools, Spain has a really low-scoring school
```

```{r pairs, fig.width=12, fig.height=12, warning=FALSE, message=FALSE}
library(YaleToolkit)
gpairs(student2012.sub.summary[, c(2, 10, 11)])
# library(cranvas)
# qstudent <- qdata(student2012.sub.summary)
# qscatter(math, read, qstudent)
# qscatter(math, science, qstudent)
# qscatter(read, science, qstudent)
# record_selector(name, qstudent)
# Should do a PCA, to look at what countries do better on what types of math skills
student2012.sub.summary.nomiss <- subset(student2012.sub.summary, !is.na(student2012.sub.summary$Change)&!is.na(student2012.sub.summary$Employ))
rownames(student2012.sub.summary.nomiss) <- student2012.sub.summary.nomiss[,1]
student2012.sub.math.pca <- prcomp(student2012.sub.summary.nomiss[,2:9], scale=T, retx=T)
student2012.sub.math.pca
qplot(PC2, PC3, data=data.frame(student2012.sub.math.pca$x)) + theme(aspect.ratio=1)
# High values on PC2 correspond to high data and interpretation, low corresponds to high spatial 
# Ireland, UK, Greece, US states, Netherland, Norway, NZ, Finland, France, Croatia, Australia come up as high 
# on data and interp but less on spatial AND
# Chine, Albania, Taiwan, Kazakhstan, Korea, Japan, Russia come up as being high on spatial, less on data and interp
rownames(student2012.sub.math.pca$x)[order(student2012.sub.math.pca$x[,2], decreasing=T)]
# High on PC3 correspond to high quantification, employ, low on data
# Israel, Croatia, Estonia, Czech are high; Taiwan, Japan, Indonesia, Massachussetts, Jordan are low
rownames(student2012.sub.math.pca$x)[order(student2012.sub.math.pca$x[,3], decreasing=T)]
student2012.sub.summary.pca <- prcomp(student2012.sub.summary.nomiss[,c(2,10,11)], scale=T, retx=T)
student2012.sub.summary.pca
```

```{r exploded-map}
oz <- subset(world.polys, name=="Australia")
oz.center <- c(mean(oz$X1), mean(oz$X2))
nz <- subset(world.polys, name=="New Zealand")
nz.center <- c(mean(nz$X1), mean(nz$X2))
ind <- subset(world.polys, name=="Indonesia")
ind.center <- c(mean(ind$X1), mean(ind$X2))
student2012.sub <- student2012[student2012$CNT=="Australia"|student2012$CNT=="New Zealand"|student2012$CNT=="Indonesia", 
                               c(1, 6, 501)]
colnames(student2012.sub)[1] <- "name"
colnames(student2012.sub)[3] <- "math"
p1 <- qplot(math, name, data=student2012.sub, xlim=c(0,1000))
summarise(group_by(student2012.sub, name), math=mean(math, na.rm=T))
oz$X1 <- scale(oz$X1, center=T, scale=T)
oz$X2 <- scale(oz$X2, center=T, scale=T)
nz$X1 <- scale(nz$X1, center=T, scale=T)
nz$X2 <- scale(nz$X2, center=T, scale=T)
ind$X1 <- scale(ind$X1, center=T, scale=T)
ind$X2 <- scale(ind$X2, center=T, scale=T)
p2 <- qplot(X1, X2, data=oz, group=group, order=order, geom="polygon") + new_theme_empty
p2 = ggplotGrob(p2)      	
p3 <- qplot(X1, X2, data=ind, group=group, order=order, geom="polygon") + new_theme_empty
p3 = ggplotGrob(p3)        
p4 <- qplot(X1, X2, data=nz, group=group, order=order, geom="polygon") + new_theme_empty
p4 = ggplotGrob(p4)        
p1 + annotation_custom(grob = p2, xmin = 900, xmax = 1000, ymin = 0.8, ymax = 1.2) +
  annotation_custom(grob = p3, xmin = 900, xmax = 1000, ymin = 1.5, ymax = 2.5) + 
  annotation_custom(grob = p4, xmin = 900, xmax = 1000, ymin = 2.5, ymax = 3.5)
```
