Seven Things That Affect Education Around the World
========================================================

Reducing inequities in education outcomes is of great interest to politicians. Dissecting the causes of inequality is a much tougher challenge with no panacea. Nonetheless, tackling inequality in educational outcomes is essential from both moral and economic viewpoints. The Programme for International Student Assessment (PISA) is a triennial survey conducted by the Organization for Economic Cooperation and Development (OECD) with a rotating additional emphasis on one of mathematics, reading, and science. In 2012, the additional emphasis was on mathematics. All 34 member countries of the OECD and 31 partnering countries and economies participated in the survey. This represents over 80% of the global economy. The OECD estimates that if all students could reach a level-2 proficiency in mathematics -- a level-2 proficiency means that a student can only handle the ``simplest and most obvious tasks" -- it would add a collective US$200 trillion to the world's collective GDP. 

The OECD describes the PISA survey as ``the world's global metric for quality, equity and efficiency in school education" (citep[p. 3]{PISA2014a}). The goal of the PISA survey is to assess the workforce readiness of 15-year old students. Nearly 500,000 students were tested across the 65 countries and economies. Students are examined on how well they can apply the knowledge they learned in school to applications outside of school. Additional information about the students, parents, and schools is also collected. The students completed a questionnaire providing information about themselves, their homes, their schools, and a variety of psychological views regarding factors they believe affects their performance in school. Schools principals responded to a questionnaire covering the school system and learning experiences for students. In some countries, parents completed a questionnaire requesting information about their perceptions regarding the school system, expectations for their child, and their involvement in their child's schooling.  


This paper will evaluate the role of several factors in which we see inequalities in mathematics, reading, and science outcomes. In section XXXgender, we will evaluate in what subjects we observe gender inequalities. In section XXX we will evaluate inequalities based on the household structure and occupation of the parents. In section XXXpossessions we will look at what home possessions are good predictors of inequalities. Lastly, in sections XXXschool, we will look at the role of school influences. 

### Teachers, computers, and libraries at school matter

### Gender gap in math is not universal but the reading gap is

### School start age affects performance

### Time spent out of school studying is important, but only up to a point

### The weird and wacky republic of Albania


